### ISSUE TITLE
Rename to pitest-mutation-testing-elements-plugin?

### ISSUE THREAD

**Issue by nicojs** [Wmaarts/pitest-mutation-testing-elements-plugin#2]
Should this plugin be renamed to mutation-testing-elements plugin? I know its not a fancy name, but Stryker doesn't have anything to do with mutation-testing-elements either. 

@hcoles do you ever want to "drop in replace" the current html reporter with this new one? If so, maybe we can call it pitest-html2-plugin or something?

**Comment by Wmaarts** [comment]
> but Stryker doesn't have anything to do with mutation-testing-elements either

Guess I misinterpreted this then, my bad. 😬

**Comment by Wmaarts** [comment]
Did some renaming (also in the code 😅).
